#!/usr/bin/env node
// EOL drift check (DT-WP-01 4.1).
// Fails when text source files carry CRLF or when .gitattributes policy is missing.
import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, extname, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

function fail(message) {
  console.error(`[eol-check] FAIL: ${message}`);
  process.exit(1);
}

function ok(message) {
  console.log(`[eol-check] ${message}`);
}

const attributesPath = join(ROOT, ".gitattributes");
if (!existsSync(attributesPath)) {
  fail("missing .gitattributes");
}
const attributes = readFileSync(attributesPath, "utf8");
for (const needle of ["text=auto eol=lf", "*.ts text eol=lf", "*.ps1 text eol=crlf"]) {
  if (!attributes.includes(needle)) fail(`.gitattributes missing rule: ${needle}`);
}
ok(".gitattributes policy present");

// Files that are allowed to carry CRLF (Windows-only launchers).
const CRLF_ALLOWED = new Set([".bat", ".cmd", ".ps1"]);
// Binary extensions are skipped.
const BINARY = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".webp",
  ".ico",
  ".woff",
  ".woff2",
  ".parquet",
  ".duckdb",
  ".db",
  ".sqlite",
]);

const SKIP_DIRS = new Set(["node_modules", ".git", ".next", "dist", "build", "coverage", ".turbo"]);
// Generated by Next.js on each build (git-ignored); Git normalization covers it on commit.
const SKIP_FILES = new Set(["next-env.d.ts"]);

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    if (entry === ".git") continue;
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (SKIP_DIRS.has(entry)) continue;
      yield* walk(full);
    } else {
      yield full;
    }
  }
}

const offenders = [];
for (const file of walk(ROOT)) {
  const base = file.split("\\").pop()?.split("/").pop() ?? file;
  if (SKIP_FILES.has(base)) continue;
  const ext = extname(file).toLowerCase();
  if (BINARY.has(ext)) continue;
  if (CRLF_ALLOWED.has(ext)) continue;
  if (file.endsWith(".gitattributes") || file.endsWith(".gitignore")) {
    // governed as LF text; still check them
  }
  let buf;
  try {
    buf = readFileSync(file);
  } catch {
    continue;
  }
  // Heuristic: skip files with NUL bytes (binary).
  if (buf.includes(0)) continue;
  // Only inspect plausible text files to keep the check fast and low-noise.
  if (
    !/\.(ts|tsx|mts|cts|js|mjs|cjs|json|jsonc|css|html|md|mdx|yml|yaml|toml|ini|sql|sh|example|editorconfig|attributes|ignore)$/.test(
      file,
    ) &&
    !file.endsWith("Dockerfile")
  ) {
    continue;
  }
  if (buf.includes("\r\n")) offenders.push(file);
}

if (offenders.length > 0) {
  console.error("[eol-check] CRLF found in LF-governed files:");
  for (const f of offenders.slice(0, 20)) console.error(`  - ${f}`);
  if (offenders.length > 20) console.error(`  ... and ${offenders.length - 20} more`);
  fail(`${offenders.length} file(s) with CRLF drift; run with LF normalization`);
}

ok("no CRLF drift in LF-governed text files");
